
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-07
owner: ucsb-cs156-f24
repo_name: team02-f24-07
pull_requests: [{"author":{"id":"U_kgDOB3EPsA","is_bot":false,"login":"kanav9063","name":""},"headRefName":"ka-team02-09","number":72,"title":" Create fixtures for UCSBDiningCommonsMenuItem #9","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/72"},{"author":{"id":"U_kgDOB3EPsA","is_bot":false,"login":"kanav9063","name":""},"headRefName":"ka-team02-08","number":71,"title":"Copy files for Backend CRUD API UCSBDiningCommonsMenuItem from team02 #8","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/71"},{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"nw-helprequest-table","number":70,"title":"Create help request table","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/70"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-article-table","number":69,"title":"Create tables component for Articles","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/69"},{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"nw-HelpRequests-form","number":68,"title":"Add Help Request Frontend Form, Storybook, and Tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/68"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-articles-form-component","number":67,"title":"Create form component for Articles","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/67"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-article-fixtures","number":66,"title":"Create fixtures for Article","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/66"},{"author":{"id":"MDQ6VXNlcjc3NjkxMTI1","is_bot":false,"login":"Ponmo","name":"Noah Wang"},"headRefName":"nw-helprequest-fixtures","number":65,"title":"Create fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/65"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-organization-fixtures","number":62,"title":"Ld organization fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/62"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-organization-backend","number":61,"title":"Ld organization backend","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/61"}]
