title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-07
owner: ucsb-cs156-f24
repo_name: team02-f24-07
pull_requests: [{"author":{"id":"U_kgDOB3EPsA","is_bot":false,"login":"kanav9063","name":""},"headRefName":"ka-team02-end2endtests","number":134,"title":"ka - end to end tests DiningCommonMenu","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/134"},{"author":{"id":"U_kgDOB3EPsA","is_bot":false,"login":"kanav9063","name":""},"headRefName":"ka-team02-e2etest","number":128,"title":"KA -Integration Tests for DiningCommonMenuItems","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/128"},{"author":{"id":"MDQ6VXNlcjc3NjkxMjgw","is_bot":false,"login":"Ramon-W","name":"Ramon Wang"},"headRefName":"rw-tests","number":122,"title":"Integration tests for Article","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/122"}]
