title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-07
owner: ucsb-cs156-f24
repo_name: team02-f24-07
pull_requests: [{"author":{"id":"U_kgDOCL-Znw","is_bot":false,"login":"divyagsubramonian","name":"Divya Subramonian"},"headRefName":"ds-recommendation-form","number":97,"title":"ds - updated Recommendation Request form","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/97"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-edit-page","number":94,"title":"Ld - Make Edit Page","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/94"},{"author":{"id":"U_kgDOBo-IIw","is_bot":false,"login":"eug-wong","name":"Eugene Wong"},"headRefName":"ew-menuItemReview-index-page","number":93,"title":"Added Index Page frontend for MenuItemReview","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/93"},{"author":{"id":"U_kgDOBo-IIw","is_bot":false,"login":"eug-wong","name":"Eugene Wong"},"headRefName":"ew-menuItemReview-create-page","number":88,"title":"Added Create Page for MenuItemReview","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/88"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-index-page","number":86,"title":"LD - Create index page","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/86"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-create-page","number":84,"title":"LD - Create Page","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/84"},{"author":{"id":"U_kgDOCL9eow","is_bot":false,"login":"lodetrick","name":""},"headRefName":"ld-pages-placeholder","number":82,"title":"LD - Copy Placeholders for UCSBOrganization Pages","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/82"},{"author":{"id":"U_kgDOB3EPsA","is_bot":false,"login":"kanav9063","name":""},"headRefName":"ka-team02-11","number":78,"title":"ka-Table Component for UCSBDiningCommonsMenuItem plus tests #11","url":"https://github.com/ucsb-cs156-f24/team02-f24-07/pull/78"}]
